title = "Liam Woodward"
base_url = "https://example.com"
description = "Liam Woodward Personal Website"

compile_sass = true
highlight_code = true
hightlight_theme = "gruvbox"

build_search_index = false

default_language = "en"

[extra]
author = { name = "Liam Woodward", email = "liamowoodward@gmail.com" }

