title = "Liam Woodward"
base_url = "https://alidiusk.github.io/"
# for testing purposes
# base_url = "127.0.0.1"
description = "Liam Woodward Personal Website"

compile_sass = true
highlight_code = true
hightlight_theme = "gruvbox"

build_search_index = false

default_language = "en"

[extra]
author = { name = "Liam Woodward", email = "liamowoodward@gmail.com" }
